"""Initial database

Revision ID: a0cf292fb8fa
Revises: 
Create Date: 2021-06-01 14:32:19.094502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import FetchedValue


# revision identifiers, used by Alembic.
revision = 'a0cf292fb8fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('d_category',
    sa.Column('id', sa.Integer(), server_default=FetchedValue(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('d_pre_pack_type',
    sa.Column('id', sa.Integer(), server_default=FetchedValue(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('d_stage',
    sa.Column('id', sa.Integer(), server_default=FetchedValue(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('d_store_section',
    sa.Column('id', sa.Integer(), server_default=FetchedValue(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('d_unit',
    sa.Column('id', sa.Integer(), server_default=FetchedValue(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dish',
    sa.Column('id', sa.Integer(), server_default=FetchedValue(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('portion', sa.Integer(), nullable=True),
    sa.Column('cook_time', sa.Integer(), nullable=True),
    sa.Column('all_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu',
    sa.Column('id', sa.Integer(), server_default=FetchedValue(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dish_categories',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('dish_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['d_category.id'], ),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.id'], )
    )
    op.create_table('foodstuff',
    sa.Column('id', sa.Integer(), server_default=FetchedValue(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('store_section_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['store_section_id'], ['d_store_section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_dishes',
    sa.Column('id', sa.Integer(), server_default=FetchedValue(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.Column('dish_id', sa.Integer(), nullable=True),
    sa.Column('portion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), server_default=FetchedValue(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=True),
    sa.Column('foodstuff_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(precision=53), nullable=True),
    sa.Column('pre_pack_type_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.id'], ),
    sa.ForeignKeyConstraint(['foodstuff_id'], ['foodstuff.id'], ),
    sa.ForeignKeyConstraint(['pre_pack_type_id'], ['d_pre_pack_type.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['d_stage.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['d_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient_alternatives',
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('foodstuff_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['foodstuff_id'], ['foodstuff.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredient_alternatives')
    op.drop_table('ingredient')
    op.drop_table('menu_dishes')
    op.drop_table('foodstuff')
    op.drop_table('dish_categories')
    op.drop_table('menu')
    op.drop_table('dish')
    op.drop_table('d_unit')
    op.drop_table('d_store_section')
    op.drop_table('d_stage')
    op.drop_table('d_pre_pack_type')
    op.drop_table('d_category')
    # ### end Alembic commands ###
