"""empty message

Revision ID: d150f0a4cc9a
Revises: 
Create Date: 2021-03-24 21:45:34.969856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd150f0a4cc9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dish', 'img')
    op.drop_constraint('fk_recipe_categories_recipes', 'dish_categories', type_='foreignkey')
    op.create_foreign_key(None, 'dish_categories', 'dish', ['dish_id'], ['id'])
    op.alter_column('foodstuff', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('foodstuff', 'store_section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('ingredients_un', 'foodstuff', type_='unique')
    op.drop_constraint('fk_ingredient_alternatives_recipe_ingredients', 'ingredient_alternatives', type_='foreignkey')
    op.create_foreign_key(None, 'ingredient_alternatives', 'ingredient', ['ingredient_id'], ['id'])
    op.alter_column('menu_dishes', 'dish_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('menu_dishes', 'menu_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('menu_dishes', 'portion',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('fk_menu_dishes_recipes', 'menu_dishes', type_='foreignkey')
    op.drop_constraint('fk_menu_dishes_menu', 'menu_dishes', type_='foreignkey')
    op.create_foreign_key(None, 'menu_dishes', 'dish', ['dish_id'], ['id'])
    op.create_foreign_key(None, 'menu_dishes', 'menu', ['menu_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menu_dishes', type_='foreignkey')
    op.drop_constraint(None, 'menu_dishes', type_='foreignkey')
    op.create_foreign_key('fk_menu_dishes_menu', 'menu_dishes', 'menu', ['menu_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_menu_dishes_recipes', 'menu_dishes', 'dish', ['dish_id'], ['id'], ondelete='CASCADE')
    op.alter_column('menu_dishes', 'portion',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('menu_dishes', 'menu_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('menu_dishes', 'dish_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'ingredient_alternatives', type_='foreignkey')
    op.create_foreign_key('fk_ingredient_alternatives_recipe_ingredients', 'ingredient_alternatives', 'ingredient', ['ingredient_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('ingredients_un', 'foodstuff', ['name'])
    op.alter_column('foodstuff', 'store_section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('foodstuff', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'dish_categories', type_='foreignkey')
    op.create_foreign_key('fk_recipe_categories_recipes', 'dish_categories', 'dish', ['dish_id'], ['id'], ondelete='CASCADE')
    op.add_column('dish', sa.Column('img', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
